Repository hypercerts-org/hypercerts-app, pull requests merged in 2024-09, with the labels that each got.

#212 Fix/uri parsing and linting
  .eslintrc.json
  .husky/commit-msg
  .husky/pre-commit
  .lintstagedrc.js
  app/hypercerts/new/page.tsx
  commitlintrc.ts
  package.json
  pnpm-lock.yaml
Labels: enhancement

#213 feat(icons): add chain icons to connector button and modal
  components/chain-display.tsx
  public/chain_icons/arbitrum.png
  public/chain_icons/arbitrum_sepolia.png
  public/chain_icons/base.png
  public/chain_icons/base_sepolia.png
  public/chain_icons/celo.png
  public/chain_icons/ethereum_sepolia.png
  public/chain_icons/optimism.png
Labels: enhancement

#215 fix(zod): validate or empty string on allowlist link
  app/hypercerts/new/page.tsx
  app/profile/[address]/hypercerts-tab-content.tsx
  app/profile/[address]/tabs.tsx
  graphql-hypercerts-env.d.ts
  hypercerts/getHypercertsByCreator.ts
  hypercerts/getHypercertsByOwner.ts
  package.json
  pnpm-lock.yaml
Labels: bug

#219 fix(copy): updates evaluation status tags
  hypercerts/getEvaluationStatus.ts
Labels: enhancement

#220 fix: remove create dropdown and add my hypercerts
  components/global/navbar.tsx
  configs/site.ts
Labels: enhancement

#221 fix(ui): max page width and increase row count
  app/evaluators/page.tsx
  components/evaluators/evaluators-list-row.tsx
  components/evaluators/evaluators-list.tsx
  components/global/navbar.tsx
  configs/ui.ts
Labels: enhancement

#224 fix(ui): navbar styling and connected chain icon
  components/chain-display.tsx
  components/global/navbar.tsx
Labels: bug, enhancement

#227 Fix/141 metadata with markdown
  .env.template
  components/read-more.tsx
  lib/utils.ts
  package.json
  pnpm-lock.yaml
Labels: enhancement

#230 feat(cache): use local storage to cache and fetch form state
  app/hypercerts/new/form-steps.tsx
  app/hypercerts/new/page.tsx
  package.json
  pnpm-lock.yaml
Labels: enhancement

#232 fix(web3): correct wc ID and update viem and wagmi
  configs/constants.ts
  configs/wagmi.ts
  package.json
  pnpm-lock.yaml
Labels: bug

#233 fix(gql): handle null response fetching allowlist records better
  allowlists/getAllowListRecordsForAddressByClaimed.tsx
  app/profile/[address]/hypercerts-tab-content.tsx
  app/profile/[address]/page.tsx
  components/profile/unclaimed-hypercert-claim-button.tsx
  components/profile/unclaimed-hypercert-list-item.tsx
  components/profile/unclaimed-hypercerts-list.tsx
  hypercerts/getHypercertsByCreator.ts
  hypercerts/getHypercertsByOwner.ts
Labels: bug

#234 chore(bump): sdks
  package.json
  pnpm-lock.yaml
Labels: bug
